-- local function find_godot_project()
--   local current_dir = vim.fn.getcwd()
--   local paths_to_check = {
--     current_dir,
--     vim.fn.fnamemodify(current_dir, ':h'),
--   }
--
--   for _, path in ipairs(paths_to_check) do
--     if vim.uv.fs_stat(path .. '/project.godot') then return path end
--   end
--   return nil
-- end
--
-- local godot_project_path = find_godot_project()
-- vim.g.is_godot_project = godot_project_path ~= nil
--
-- if vim.g.is_godot_project then
--   local pipe_path = godot_project_path .. '/server.pipe'
--
--   if vim.uv.fs_stat(pipe_path) then os.remove(pipe_path) end
--
--   local success, server_addr = pcall(vim.fn.serverstart, pipe_path)
--   if success then
--     print('Godot server started at: ' .. pipe_path)
--   else
--     print('Failed to start Godot server: ' .. tostring(server_addr))
--   end
-- end

--[[
--  Godot settings:
--
--  Text Editor -> External ->
--    Use External Editor = true
--    Exec Path = `/usr/bin/nvim`
--    Exec Flags = `--server {project}/server.pipe --remote-send "<C-\><C-N>:e {file}<CR>:call cursor({line}+1,{col})<CR>"`
--
--  Editor Settings -> Network -> Language Server -> Use Thread = true
--
--
--]]
