indent_type = "Spaces"
indent_width = 2
column_width = 80
quote_style = "AutoPreferSingle"
line_endings = "Unix"
call_parentheses = "Always"
space_after_function_names = "Never"
collapse_simple_statement = "Always"

